apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopper-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: shopper
        image: sanixsandel/shopper:1.0.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5555
        env:
        - name: GROCERY_URL
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: grocery_url


---
apiVersion: v1
kind: Service
metadata:
 name: shopper-service
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - port: 9000
    targetPort: 5555
    nodePort: 30001
