# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protofiles import proto_pb2 as proto__pb2


class notifyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.send_notif = channel.unary_unary(
                '/notify/send_notif',
                request_serializer=proto__pb2.DataRequest.SerializeToString,
                response_deserializer=proto__pb2.DataResponse.FromString,
                )


class notifyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def send_notif(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_notifyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'send_notif': grpc.unary_unary_rpc_method_handler(
                    servicer.send_notif,
                    request_deserializer=proto__pb2.DataRequest.FromString,
                    response_serializer=proto__pb2.DataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notify', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class notify(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def send_notif(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notify/send_notif',
            proto__pb2.DataRequest.SerializeToString,
            proto__pb2.DataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
