# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproto.proto\"+\n\x0b\x44\x61taRequest\x12\r\n\x05total\x18\x01 \x01(\x03\x12\r\n\x05items\x18\x02 \x03(\t\"\x1f\n\x0c\x44\x61taResponse\x12\x0f\n\x07message\x18\x01 \x01(\t23\n\x06notify\x12)\n\nsend_notif\x12\x0c.DataRequest\x1a\r.DataResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATAREQUEST._serialized_start=15
  _DATAREQUEST._serialized_end=58
  _DATARESPONSE._serialized_start=60
  _DATARESPONSE._serialized_end=91
  _NOTIFY._serialized_start=93
  _NOTIFY._serialized_end=144
# @@protoc_insertion_point(module_scope)
